"""Domain models (L0).

Pure data: frozen dataclasses, enumerations, identifiers and validation. No I/O,
no SQL, no configuration. Persisting these objects is the job of `app.storage`.

Decisions in force here:

* ADR 0005 - frozen `dataclass` with `slots=True`; `validate()` returns
  `Result[None]` whose `Err` lists every problem at once; integrity is enforced
  again by the database schema.
* ADR 0006 - identifiers are `<PREFIX>-<8+ digits>`.
* Timestamps are ISO-8601 in UTC with a `Z` suffix, so lexicographic order equals
  chronological order (approved 2026-09-20).
"""

from app.models.base import (
    TIMESTAMP_PATTERN,
    is_valid_timestamp,
    parse_timestamp,
    utc_now,
    validation_failure,
)
from app.models.entities import (
    ALL_ENTITIES,
    ENTITIES,
    PHASE_3_ENTITIES,
    PHASE_4_ENTITIES,
    PHASE_5_ENTITIES,
    PHASE_6_ENTITIES,
    PHASE_8_ENTITIES,
    Action,
    AuditEvent,
    Calculation,
    Concept,
    ConceptAlias,
    ConceptEquivalence,
    ConceptOccurrence,
    Conflict,
    Derivation,
    Document,
    DocumentSegment,
    DocumentStructure,
    DocumentVersion,
    Equation,
    ExecutionPlan,
    ExtractionIssue,
    ExtractionRun,
    Intent,
    KnowledgeEquivalence,
    KnowledgeObject,
    MemoryItem,
    Procedure,
    Query,
    Relationship,
    RelationshipInference,
    RelationshipOccurrence,
    Rule,
    Source,
    SourceOccurrence,
    Variable,
    Verification,
)
from app.models.enums import (
    Authorization,
    CertaintyState,
    ConceptEquivalenceBasis,
    ConceptEquivalenceStatus,
    ConflictCause,
    DocumentKind,
    DocumentProcessingStatus,
    ExtractionIssueType,
    ExtractionRunStatus,
    ExtractionTrigger,
    KnowledgeEquivalenceOutcome,
    KnowledgeType,
    LifecycleStatus,
    MemoryCategory,
    ProcedureDocumentationStatus,
    RelationshipOrigin,
    RelationType,
    RiskLevel,
    SourceAvailability,
    SourceCategory,
    StructureOrigin,
    TaskClass,
    TextOrigin,
    VerificationStatus,
)
from app.models.naming import NORMALIZATION_VERSION, normalize_alias
from app.models.views import AttachedKnowledge, ConceptView
from app.models.identifiers import (
    ID_PATTERN,
    MIN_DIGITS,
    EntityKind,
    format_id,
    is_valid_id,
    parse_id,
)

__all__ = [
    "Action",
    "ALL_ENTITIES",
    "AttachedKnowledge",
    "AuditEvent",
    "Authorization",
    "Calculation",
    "CertaintyState",
    "Concept",
    "ConceptAlias",
    "ConceptEquivalence",
    "ConceptEquivalenceBasis",
    "ConceptEquivalenceStatus",
    "ConceptOccurrence",
    "ConceptView",
    "Conflict",
    "ConflictCause",
    "Derivation",
    "Document",
    "DocumentKind",
    "DocumentProcessingStatus",
    "DocumentSegment",
    "DocumentStructure",
    "DocumentVersion",
    "ENTITIES",
    "EntityKind",
    "Equation",
    "ExecutionPlan",
    "ExtractionIssue",
    "ExtractionIssueType",
    "ExtractionRun",
    "ExtractionRunStatus",
    "ExtractionTrigger",
    "format_id",
    "ID_PATTERN",
    "Intent",
    "is_valid_id",
    "is_valid_timestamp",
    "KnowledgeEquivalence",
    "KnowledgeEquivalenceOutcome",
    "KnowledgeObject",
    "KnowledgeType",
    "LifecycleStatus",
    "MemoryCategory",
    "MemoryItem",
    "MIN_DIGITS",
    "NORMALIZATION_VERSION",
    "normalize_alias",
    "parse_id",
    "parse_timestamp",
    "PHASE_3_ENTITIES",
    "PHASE_4_ENTITIES",
    "PHASE_5_ENTITIES",
    "PHASE_6_ENTITIES",
    "PHASE_8_ENTITIES",
    "Procedure",
    "ProcedureDocumentationStatus",
    "Query",
    "Relationship",
    "RelationshipInference",
    "RelationshipOccurrence",
    "RelationshipOrigin",
    "RelationType",
    "RiskLevel",
    "Rule",
    "Source",
    "SourceAvailability",
    "SourceCategory",
    "SourceOccurrence",
    "StructureOrigin",
    "TaskClass",
    "TextOrigin",
    "TIMESTAMP_PATTERN",
    "utc_now",
    "validation_failure",
    "Variable",
    "Verification",
    "VerificationStatus",
]
